import { createContext, useContext, useState, useEffect, useRef, type ReactNode } from "react";

export type Lang = "en" | "es";

const LS_KEY = "goaliq_lang";

const T: Record<Lang, Record<string, string>> = {
  en: {
    // ── Navigation ────────────────────────────────────────────────────────────
    nav_home: "Home",
    nav_meals: "Meals",
    nav_shopping: "Shopping",
    nav_workouts: "Workouts",
    nav_calendar: "Calendar",
    nav_progress: "Progress",

    // ── Profile menu ──────────────────────────────────────────────────────────
    my_profile: "My Profile",
    billing: "Billing",
    sign_out: "Sign Out",

    // ── Trial sidebar ─────────────────────────────────────────────────────────
    trial_ends_today: "Trial ends today",
    trial_days_left_one: "1 day left in trial",
    trial_days_left_n: "Trial · {{n}} days left",

    // ── Dashboard ─────────────────────────────────────────────────────────────
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    weekly_training: "Weekly Training",
    todays_meals: "Today's Meals",
    this_week: "This Week",
    weight_label: "Weight",
    adherence_label: "Adherence",
    workouts_label: "Workouts",
    no_plan_yet: "No plan yet",
    view_plan: "View plan",
    generate_plan: "Generate plan",
    rest_today: "Rest today",
    no_meals_today: "No meals logged for today",
    no_workouts_today: "No training scheduled today",
    view_all_meals: "View all meals →",
    view_workout: "View workout →",
    trial_active_days: "Trial active — {{n}} days left",
    trial_1_day_left: "1 day left in your trial",
    subscribe_now: "Subscribe now to keep full access",
    free_until: "Free until {{date}} · then €19.99/month",
    free_trial_no_charge: "Free trial — no charge yet",
    subscribe: "Subscribe",
    manage: "Manage",
    exercises_n: "{{n}} exercises",
    completed_check: "completed ✓",
    today: "Today",
    current_weight: "Current weight",
    from_start: "from start",
    weekly_adherence_label: "Weekly adherence",
    workouts_done_this_week: "{{done}} of {{total}} workouts completed this week",
    view_my_workouts: "View my workouts",
    log_my_weight: "Log my weight",
    workout_completed_toast: "Workout completed! 🎉",
    share_in_workouts: "Share it in Workouts →",
    close: "Close",
    rest_duration: "{{min}} min rest",
    rest_seconds: "{{n}}s rest",
    duration_label: "Duration",
    day_mon: "Mon",
    day_tue: "Tue",
    day_wed: "Wed",
    day_thu: "Thu",
    day_fri: "Fri",
    day_sat: "Sat",
    day_sun: "Sun",
    light_stretching: "Light stretching or a walk is perfect",
    ingredients_n: "{{n}} ingredients",
    no_meals_today_plan: "No meals planned for today.",
    meal_plan_after_onboarding: "Your meal plan will appear here after onboarding.",
    view_meals: "View Meals",
    adherence_pct_week: "{{n}}% adherence this week",
    track_workouts: "Track workouts",
    share_progress: "Share my progress",
    first_exercise: "First exercise",
    start_workout: "Start workout",
    shopping_pending: "{{n}} pending",
    shopping_this_week: "Shopping list this week",
    view_full_list: "View full list →",
    view_full_plan: "View full plan →",
    day_streak: "day streak",
    completed_pct: "{{n}}% complete",
    workouts_x_of_y: "{{done}} of {{total}} workouts",
    target_weight: "Target: {{n}}kg",

    // ── Profile dashboard ─────────────────────────────────────────────────────
    total_workouts: "Total Workouts",
    this_month_label: "This Month",
    streak_days: "Day Streak",
    avg_duration_label: "Avg Duration",
    weekly_volume_label: "Weekly Volume",
    last_session_label: "Last Session",
    muscle_groups_label: "Muscle Groups",
    no_sessions_yet: "No sessions yet",
    view_detail_btn: "View detail →",
    vs_prev_week: "vs prev. week",
    days_done_fmt: "{{done}} / {{total}} days",
    chart_range_4w: "4W",
    chart_range_3m: "3M",
    chart_range_1y: "1Y",
    mins_short: "min",
    hrs_this_week: "hrs this week",
    no_data: "No data yet",

    // ── Meals ─────────────────────────────────────────────────────────────────
    weekly_menu: "Weekly Menu",
    new_plan: "New plan",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    ingredients_portions: "Ingredients & Portions",
    replace_ingredient: "Replace ingredient",
    generating_meal_plan: "Generating your new meal plan — this takes about 30 seconds…",
    complete_profile_first: "Complete your profile first",
    no_meal_plan_yet: "No meal plan yet",
    generate_btn: "Generate",
    generate: "Generate",
    cancel_btn: "Cancel",
    cancel: "Cancel",
    replace_this_week: "Replace this week's meals with a fresh AI-generated plan?",
    replace_plan_confirm: "Replace this week's meals with a fresh AI-generated plan?",
    profile_incomplete: "Profile incomplete",
    complete_profile_title: "Complete your profile first",
    complete_profile_body: "We need to know your diet type and goal to generate a personalised meal plan tailored to you.",
    complete_my_profile: "Complete My Profile",
    no_meal_plan_onboarding: "Complete the onboarding to get your personalised 7-day meal plan generated automatically.",
    week_of: "Week of",
    update_profile: "Update profile",
    generating_short: "Generating…",
    generation_failed: "Generation failed",
    update_profile_btn: "Update Profile",
    update_now: "Update now",
    no_meals_this_day: "No meals planned for this day.",
    plate_guide: "Plate Guide",
    distribution: "Distribution",
    pg_protein: "¼ plate",
    pg_carbs: "¼ plate",
    pg_vegetables: "½ plate",
    pg_fruit: "small serving",
    pg_fats: "small amount",
    pg_dairy: "small serving",
    pg_other: "to taste",
    please_complete_profile: "Please complete your profile before generating a new plan.",
    view_restrictions_arrow: "View your restrictions →",
    no_suitable_alts: "No suitable alternatives found for this ingredient.",
    could_not_load_swaps: "Could not load swap options. Please try again.",
    swap_failed: "Swap failed. Please try again.",

    // ── Workouts ──────────────────────────────────────────────────────────────
    weekly_training_title: "Weekly Training",
    todays_focus: "Today's Focus",
    session_focus: "Session Focus",
    exercises_label: "Exercises",
    view_example: "View example",
    view_example_arrow: "View example →",
    rest_label: "Rest",
    rest_short: "Rest",
    no_workout_yet: "No workout plan yet",
    no_workout_plan: "No workout plan yet",
    training_days_count: "{{n}} training days this week",
    rest_recover: "Rest & Recover",
    rest_recover_msg: "Rest days are just as important as training. Light walking, stretching, or yoga are perfect today.",
    complete_onboarding_workout: "Complete the onboarding to get your personalized weekly training plan generated automatically.",
    wt_cardio: "Cardio",
    wt_hiit: "HIIT",
    wt_circuit: "Circuit",
    wt_upper: "Upper Body",
    wt_lower: "Lower Body",
    wt_full: "Full Body",
    wt_push: "Push Day",
    wt_pull: "Pull Day",
    wt_legs: "Leg Day",
    wt_core: "Core Day",
    wt_cardio_day: "Cardio Day",
    sets_x_reps: "{{sets}} sets × {{reps}} reps",
    rest_duration: "{{duration}} rest",
    start: "Start",
    end: "End",

    // ── Calendar ──────────────────────────────────────────────────────────────
    calendar_title: "📅 Calendar",
    flex_day_tracker: "Flex Day Tracker",
    flex_day_desc: "Diet free day — eat without restrictions",
    flex_month_count: "{{n}} / 4 this month",
    flex_limit_exceeded: "You've exceeded the recommended limit",
    flex_limit_toast: "You have {{n}} Flex Days this month — careful not to overdo it! 😋",
    monthly_adherence: "Monthly adherence",
    completed_label: "Completed",
    planned_workout: "Planned workout",
    rest_day: "Rest day",
    flex_day: "Flex Day",
    workouts_done: "{{done}} of {{total}} workouts done",
    workouts_done_of: "{{done}} of {{total}} workouts done",
    adherence_perfect_month: "Perfect month! Every workout completed.",
    adherence_crushing: "You're crushing it — elite consistency!",
    adherence_strong_month: "Strong month. Keep building the habit.",
    adherence_good_effort: "Good effort! Push a little harder each week.",
    adherence_started: "You've started — every completed workout counts.",
    adherence_fresh_month: "A fresh month awaits. Tap any workout day to log it.",
    clean_weeks: "{{n}} week{{s}} of clean eating — impressive willpower!",
    flex_days_across: "{{n}} flex day{{s}} used across {{weeks}} week{{ws}} — balance is key.",
    keep_going: "keep going!",
    tap_workout_hint: "Tap a workout day to mark complete · Tap 😋 to mark a Flex Day",
    flex_day_used_week: "You already have a Flex Day this week 😋",
    only_one_flex: "You can only mark one Flex Day per week.",
    could_not_save_flex: "Could not save Flex Day. Please try again.",
    mark_as_done: "Mark as complete",
    confirm: "Confirm",

    // ── Strength tracking ──────────────────────────────────────────────────────
    log_todays_max: "Log today's max",
    strength_progress: "Strength progress",
    personal_record: "Personal record!",
    new_pr: "+{{n}}kg new record",
    prev_record: "Previous: {{n}}kg",
    save_log: "Save",
    no_strength_data: "Start logging weights to see your progress",
    select_muscle: "Select muscle group",
    muscle_group_shoulders: "Shoulders",
    muscle_group_back: "Back",
    muscle_group_legs: "Legs",
    muscle_group_chest: "Chest",
    muscle_group_arms: "Arms",
    muscle_group_core: "Core",
    log_timed: "Log time",
    target_time: "Target",
    seconds_unit: "sec",
    actual_time: "Actual time (sec)",
    log_cardio: "Log cardio session",
    log_bodyweight: "Log reps",
    distance_km: "Distance (km)",
    duration_min: "Time (min)",
    pace_label: "Pace (min/km)",
    heart_rate: "Avg HR (bpm)",
    sets_done: "Sets done",
    optional_field: "Optional",

    // ── Shopping ──────────────────────────────────────────────────────────────
    shopping_list: "Shopping List",
    vegetables: "Vegetables",
    fruits: "Fruits",
    fruit: "Fruit",
    protein: "Protein",
    dairy: "Dairy",
    carbs: "Carbs",
    carbohydrates: "Carbohydrates",
    fat: "Fat",
    fats: "Fats",
    other: "Other",
    add_custom_item: "Add custom item",
    clear_purchased: "Clear",
    clear: "Clear",
    category_label: "Category",
    supermarket_label: "Supermarket",
    optimize_label: "Optimize",
    purchased_count: "{{n}} of {{total}} purchased",
    all_purchased: "All purchased! 🎉",
    items_label: "items",
    cat_done_label: "DONE ✓",
    categories_label: "categories",
    custom_label: "custom",
    show_n: "Show ({{n}})",
    hide_n: "Hide ({{n}})",
    updates_automatically: "Updates automatically when you swap ingredients",
    most_needed: "Most-needed items first — sorted by how many meals use them",
    no_meal_plan_shopping: "Generate your weekly meal plan to automatically get a personalized shopping list.",
    go_to_meals: "Go to Meals",

    // ── Progress ──────────────────────────────────────────────────────────────
    progress_title: "📈 Progress",
    weight_title: "Weight",
    log_weight: "Log weight",
    log_today_weight: "Log Today's Weight",
    current_weight: "Current Weight",
    start_weight: "Start Weight",
    target_weight: "Target",
    your_goal: "Your Goal",
    save_btn: "Save",
    saved: "Saved!",
    kg_logged: "{{n}} kg logged!",
    workouts_done_label: "Workouts Done",
    weekly_adherence_label: "Weekly Adherence",
    weight_over_time: "Weight Over Time",
    your_journey: "Your journey so far",
    recent_entries: "Recent Entries",
    no_target_weight: "No target weight set",
    every_workout_counts: "Every workout counts 🎯",
    this_week_short: "this week",
    press_plus: "Press + to save your weight",
    eg_weight: "e.g. 72.5",
    not_enough_data: "Not enough data yet",
    log_to_see_trend: "Log your weight a few times to see your trend",
    goal_reached: "🎉 Goal reached!",
    kg_to_go: "{{n}} kg to go",
    log_first_weigh_in: "Log your first weigh-in below",
    from_start: "from start",
    down_kg_progress: "Down {{n}} kg — great progress!",
    up_kg_from_start: "Up {{n}} kg from starting weight",
    weight_stable: "Weight stable since you started",
    goal_hit_congrats: "You've hit your goal weight — incredible!",
    kg_to_goal_over: "{{n}} kg to your goal. Keep going — you're making progress!",
    kg_to_goal_almost: "{{n}} kg to your goal. Almost there!",
    great_tracking: "Great job tracking today. Consistency is everything.",
    trending_right: "{{n}} kg to your goal. You're trending in the right direction — stay consistent.",
    keep_logging: "Keep logging your weight to track your momentum.",
    normal_muscle_gain: "This is normal — muscle gain can show as weight gain. Stay the course and trust the plan.",
    consistency_logging: "Consistency in logging will reveal your trend over time. Keep it up!",
    adherence_excellent: "Excellent! Keep it up 🏆",
    adherence_good_progress: "Good progress 💪",

    // ── Profile page ──────────────────────────────────────────────────────────
    profile_title: "My Profile & Preferences",
    profile_subtitle: "Applied to every meal plan and ingredient swap",
    profile_incomplete_title: "Your profile is incomplete",
    profile_incomplete_body: "Complete your profile to generate your personalised meal plan. Missing:",
    complete_my_profile_btn: "Complete My Profile",
    your_name: "Your Name",
    diet_type_label: "Diet Type",
    goal_label: "Goal",
    allergies_label: "Allergies",
    intolerances_label: "Intolerances",
    disliked_foods_label: "Disliked Foods",
    favourite_foods_label: "Favourite Foods",
    name_not_set: "Not set — add your name via Update Preferences",
    not_set_complete: "Not set — please complete your profile",
    no_allergies: "No allergies recorded",
    no_dislikes: "No dislikes recorded",
    no_favourites: "No favourites recorded",
    missing_badge: "Missing",
    restrictions_applied: "Your dietary restrictions are applied to every meal plan, shopping list, and ingredient swap.",
    strictly_excluded: "These are strictly excluded from all generated meals and ingredient swaps — including all derivatives and related products.",
    dislikes_excluded: "These foods are excluded from meal plans and won't appear as ingredient swap suggestions.",
    ai_includes_likes: "The AI tries to include these foods where possible and appropriate for your diet.",
    saving_regenerates: "Saving updated preferences will automatically regenerate your meal plan within about 30 seconds.",
    current_label: "Current",
    update_preferences: "Update Preferences",
    back_to_billing: "Back to Billing",

    // ── Billing page ──────────────────────────────────────────────────────────
    billing_title: "Subscription & Billing",
    billing_subtitle: "Manage your GoalIQ plan",
    back_to_dashboard: "Back to Dashboard",
    plan_details: "Plan Details",
    plan_label: "Plan",
    price_label: "Price",
    status_label: "Status",
    trial_ends_label: "Trial ends",
    billing_monthly_label: "Billing",
    trial_active_badge: "Trial Active",
    active_badge: "Active",
    payment_overdue_badge: "Payment Overdue",
    canceled_badge: "Canceled",
    no_plan_badge: "No Plan",
    manage_subscription: "Manage subscription",
    whats_included: "What's included",
    monthly_billing: "Monthly",
    ends_today: "ends today",
    one_day_left: "1 day left",
    n_days_left: "{{n}} days left",
    payments_secured: "Payments secured by Stripe · Cancel anytime",
    trial_desc: "You have full access during your free trial.",
    active_desc: "Your subscription is active. Full access enabled.",
    past_due_desc: "Your last payment failed. Update your payment method to keep access.",
    canceled_desc: "Your subscription was canceled. Resubscribe to regain access.",
    no_plan_resubscribe: "Resubscribe for €19.99/month to restore full access.",
    no_plan_trial: "Start your free trial to unlock all features.",
    feat_meal_plan: "Full 7-day personalized meal plan",
    feat_workout: "Complete weekly workout schedule",
    feat_ingredient_swap: "Ingredient swapping (AI-powered)",
    feat_weight: "Weight tracking & progress charts",
    feat_insights: "Smart coaching insights",
    feat_streak: "Streak tracking & calendar",

    // ── Pricing / Trial Copy ───────────────────────────────────────────────────
    back_to_home: "Back to home",
    one_plan_everything: "ONE PLAN. EVERYTHING INCLUDED.",
    go_to_dashboard: "Go to Dashboard",
    per_month: "/month",
    price_monthly_display: "€19.99/month",
    after_trial_note: "After your trial, you'll be charged €19.99/month. Cancel anytime — no questions asked.",
    pricing_manage: "Manage",
    pricing_status_trial: "Free Trial",
    pricing_status_active: "Active",
    pricing_status_past_due: "Payment overdue",
    pricing_status_canceled: "Canceled",
    pricing_status_unpaid: "Unpaid",
    confirming_with_stripe: "Confirming your subscription with Stripe",
    page_workout_plan: "Workout Plan",
    page_workout_calendar: "Workout Calendar",
    page_meal_plan: "Meal Plan",
    page_shopping_list: "Shopping List",
    page_progress: "Progress Tracking",
    unlock_full_access: "Unlock full access",
    pricing_feat_1: "Full 7-day personalized meal plan",
    pricing_feat_shopping: "🛒 Automatic shopping list — generated from your weekly plan",
    pricing_feat_2: "Complete weekly workout schedule",
    pricing_feat_3: "Ingredient swapping (AI-powered)",
    pricing_feat_4: "Weight tracking & progress charts",
    pricing_feat_5: "Smart coaching insights",
    pricing_feat_6: "Streak tracking & adherence stats",
    pricing_feat_7: "Calendar with workout logging",
    pricing_feat_8: "Weight trend analysis",
    trial_feat_1: "Full 7-day personalized meal plan",
    trial_feat_2: "Complete weekly workout schedule",
    trial_feat_3: "AI-powered ingredient swapping",
    trial_feat_4: "Weight & progress tracking",
    trial_feat_5: "Smart coaching insights & streak tracking",
    tc_tagline: "Free for 3 days — then €19.99/month. Cancel anytime.",
    tc_tagline_short: "No charge for 3 days · Cancel anytime",
    tc_badge: "3-DAY FREE TRIAL",
    tc_price_after_trial: "Free for 3 days, then €19.99/month · Cancel anytime",
    tc_pricing_subheading: "Start free for 3 days — no charge during trial. Cancel anytime.",
    tc_secured_by_stripe: "Secured by Stripe · No charge during trial",
    tc_full_access_trial: "Full access during your 3-day trial",
    tc_available_trial: "Available during your free 3-day trial and with an active subscription.",
    tc_cta_start: "Start your 3-day free trial",
    tc_cta_start_short: "Start Free Trial",
    tc_cta_signup: "Sign Up & Start Free Trial",
    tc_cta_redirecting: "Redirecting to checkout…",
    tc_cta_subscribe: "Subscribe",
    tc_cta_resubscribe: "Resubscribe",
    tc_cta_add_payment: "Add Payment Method",
    tc_cta_unlock: "Trial — Unlock",
    tc_cta_start_free: "Start free trial",
    tc_trial_note: "3-day free trial · No charge today · Cancel anytime",
    tc_no_card_charge: "€0 charged during your 3-day trial · Cancel anytime",
    tc_resubscribe_title: "Restore your full access",
    tc_resubscribe_subtitle: "Resubscribe for €19.99/month and continue your personalized meal plans, workouts, and progress.",
    tc_resubscribe_badge: "RESUBSCRIBE",
    tc_resubscribe_price_note: "€19.99/month · Billed monthly · Cancel anytime",
    tc_resubscribe_cta: "Resubscribe — €19.99/month",
    tc_resubscribe_note: "Billed monthly · Cancel anytime",
    tc_resubscribe_secured: "Secured by Stripe · Billed monthly",
    tc_resubscribe_gate: "Your subscription has ended. Resubscribe to regain full access.",
    tc_countdown_ends_today: "Your free trial ends today",
    tc_countdown_one_day: "1 day left in your free trial",
    tc_countdown_n_days: "{{n}} days left in your free trial",
    tc_countdown_cta: "Subscribe",
    tc_countdown_urgent: "Don't lose your personalized plan — subscribe to keep access",
    tc_countdown_enjoy: "Subscribe now to keep your personalized plan and progress after your trial",
    tc_payment_overdue: "Your payment is overdue. Please update your payment method to continue.",
    tc_sub_canceled: "Your subscription was canceled. Resubscribe to regain access.",
    tc_success_title: "You're all set!",
    tc_success_body: "Your 3-day free trial has started. Enjoy full access to GoalIQ — no charge until your trial ends.",
    tc_success_footer: "We'll remind you before your trial ends. Cancel anytime from your billing page.",
    tc_success_redirecting: "Taking you to your dashboard…",
    tc_resub_success_body: "Your subscription is now active. Welcome back — full access has been restored.",
    tc_resub_success_footer: "You'll be billed €19.99/month. Cancel anytime from your billing page.",
    tc_activating_subscription: "Activating your subscription…",
    tc_activating_trial: "Activating your trial…",

    // ── Onboarding ────────────────────────────────────────────────────────────
    onboarding_step_about: "About You",
    onboarding_step_diet: "Your Diet",
    onboarding_step_fitness: "Your Fitness",
    onboarding_subtitle_about: "Help us personalise your plan",
    onboarding_subtitle_diet: "What you eat and love",
    onboarding_subtitle_fitness: "How you like to move",
    loading_preferences: "Loading your preferences…",
    updating_preferences_msg: "Updating your preferences — your meal plan will regenerate automatically when you save.",
    what_call_you: "What should we call you?",
    personalise_hint: "This helps us personalise your coaching experience.",
    how_old: "How old are you?",
    bio_sex: "Biological sex",
    sex_male: "Male",
    sex_female: "Female",
    sex_other: "Other",
    height_cm: "Height (cm)",
    current_weight_kg: "Current weight (kg)",
    main_goal: "What's your main goal?",
    goal_lose_fat: "Lose Fat",
    goal_stay_fit: "Stay Fit",
    goal_build_muscle: "Build Muscle",
    target_weight_kg: "Target weight (kg)",
    diet_type_question: "What type of diet do you follow?",
    diet_balanced: "Balanced",
    diet_high_protein: "High Protein",
    diet_keto: "Keto",
    diet_vegetarian: "Vegetarian",
    diet_vegan: "Vegan",
    food_allergies: "Any food allergies?",
    leave_blank: "Leave blank if none",
    allergies_placeholder: "e.g. nuts, dairy, shellfish",
    foods_avoid: "Foods you'd rather avoid?",
    foods_avoid_placeholder: "e.g. mushrooms, olives, broccoli",
    foods_love: "Foods you love?",
    foods_love_hint: "The AI will try to include these",
    foods_love_placeholder: "e.g. chicken, avocado, berries",
    fitness_level: "What's your fitness level?",
    fitness_beginner: "Beginner",
    fitness_intermediate: "Intermediate",
    fitness_advanced: "Advanced",
    where_workout: "Where do you prefer to work out?",
    gym: "Gym",
    home: "Home",
    outdoor: "Outdoor",
    training_days_slider: "How many days per week can you train? — {{n}} days",
    one_day: "1 day",
    seven_days: "7 days",
    couldnt_save_prefs: "Couldn't save preferences",
    couldnt_create_plan: "Couldn't create your plan",
    back: "Back",
    continue_btn: "Continue",
    saving_regenerating: "Saving & regenerating…",
    creating_plan: "Creating your plan...",
    save_regenerate: "Save & Regenerate Plan",
    lets_go: "Let's go!",
    step_n_of_m: "Step {{n}} of {{m}}",
    update_prefix: "Update:",
    new_plan_30s: "Your new meal plan will be ready in about 30 seconds",
    can_update_later: "You can always update this later",
    target_weight_placeholder: "e.g. 65",
    name_placeholder: "e.g. Alex",

    done_name: "Done, {{name}}!",
    done: "Done!",

    // ── Buttons ───────────────────────────────────────────────────────────────
    start_free_trial: "Start Free Trial",
    generate_new_plan: "Generate new plan",

    // ── Dashboard feedback messages ───────────────────────────────────────────
    fb_fire_title_name: "You're absolutely on fire, {{name}}!",
    fb_fire_title: "You're absolutely on fire!",
    fb_fire_msg: "{{n}} training sessions completed in a row. That's elite-level consistency — most people never get here.",
    fb_fire_tip: "Recovery matters too — keep sleeping 7-9h and eating enough protein.",
    fb_streak_title: "Building serious momentum",
    fb_streak_msg: "{{n}} training days in a row and counting. This is exactly how lasting habits are built.",
    fb_streak_tip: "Keep going — at 7 days you earn your first flame badge!",
    fb_done_title: "Today's workout: complete!",
    fb_done_msg_name: "{{name}}, you showed up and got it done. Rest, eat well, and let your body recover and grow.",
    fb_done_msg: "You showed up and got it done. Rest, eat well, and let your body recover and grow.",
    fb_done_tip: "Post-workout nutrition: aim for protein + carbs within 30-60 minutes.",
    fb_perfect_title_name: "Flawless week, {{name}}!",
    fb_perfect_title: "Flawless week so far!",
    fb_perfect_msg: "Every planned workout completed. You've set the bar for yourself and cleared it.",
    fb_perfect_tip: "Celebrate small wins — they compound into big results.",
    fb_solid_title: "Solid week in progress",
    fb_solid_msg: "{{done}} of {{total}} workouts done. You're showing up consistently — that's what matters.",
    fb_solid_tip_more: "One more session to make it perfect!",
    fb_keep_title: "Keep the momentum going",
    fb_keep_msg: "{{done}} of {{total}} done this week. Every session you complete makes the next one easier.",
    fb_keep_tip: "Tip: Schedule your next workout right now — treat it like a meeting you can't cancel.",
    fb_started_title: "You've started — that's huge",
    fb_started_msg: "One workout done this week. The first one is always the hardest. Now build on it.",
    fb_started_tip: "Research shows: people who do 2+ workouts per week are 80% more likely to stick long-term.",
    fb_fresh_title: "A new week, a fresh start",
    fb_fresh_msg: "Your workouts are planned and waiting. Every champion started exactly where you are right now.",
    fb_fresh_tip: "Even 20 minutes counts. Start small, stay consistent.",
    fb_rest_title: "Rest & recharge today",
    fb_rest_msg: "Recovery is part of the plan. Stay hydrated, eat well, and let your body do its work.",
    badge_streak_fire: "{{n}}-Day Streak 🔥",
    badge_streak_zap: "{{n}}-Day Streak ⚡",
    badge_perfect: "Perfect Week 🏆",
    badge_done: "Done for today ✓",

    // ── Calendar flex day feedback ─────────────────────────────────────────────
    flex_none_msg: "No flex days used this month — great discipline!",
    flex_used_msg: "{{n}} flex day{{s}} used across {{weeks}} week{{ws}} — balance is key.",

    // ── Settings ──────────────────────────────────────────────────────────────
    nav_settings: "Settings",
    settings_title: "Settings",
    appearance: "Appearance",
    dark_mode: "Dark",
    light_mode: "Light",
    language_section: "Language",
    lang_spanish: "Español",
    lang_english: "English",
    lang_subtitle_es: "España",
    lang_subtitle_en: "United Kingdom",
  },

  es: {
    // ── Navigation ────────────────────────────────────────────────────────────
    nav_home: "Inicio",
    nav_meals: "Comidas",
    nav_shopping: "Compra",
    nav_workouts: "Entrenos",
    nav_calendar: "Calendario",
    nav_progress: "Progreso",

    // ── Profile menu ──────────────────────────────────────────────────────────
    my_profile: "Mi perfil",
    billing: "Facturación",
    sign_out: "Cerrar sesión",

    // ── Trial sidebar ─────────────────────────────────────────────────────────
    trial_ends_today: "La prueba termina hoy",
    trial_days_left_one: "1 día restante en prueba",
    trial_days_left_n: "Prueba · {{n}} días restantes",

    // ── Dashboard ─────────────────────────────────────────────────────────────
    greeting_morning: "Buenos días",
    greeting_afternoon: "Buenas tardes",
    greeting_evening: "Buenas noches",
    weekly_training: "Entrenamiento semanal",
    todays_meals: "Comidas de hoy",
    this_week: "Esta semana",
    weight_label: "Peso",
    adherence_label: "Adherencia",
    workouts_label: "Entrenamientos",
    no_plan_yet: "Sin plan aún",
    view_plan: "Ver plan",
    generate_plan: "Generar plan",
    rest_today: "Descanso hoy",
    no_meals_today: "Sin comidas registradas hoy",
    no_workouts_today: "Sin entrenamiento programado hoy",
    view_all_meals: "Ver todas las comidas →",
    view_workout: "Ver entrenamiento →",
    trial_active_days: "Prueba activa — {{n}} días restantes",
    trial_1_day_left: "1 día restante en tu prueba",
    subscribe_now: "Suscríbete ahora para mantener el acceso completo",
    free_until: "Gratis hasta {{date}} · luego €19.99/mes",
    free_trial_no_charge: "Prueba gratuita — sin cargo aún",
    subscribe: "Suscribirse",
    manage: "Gestionar",
    exercises_n: "{{n}} ejercicios",
    completed_check: "completado ✓",
    today: "Hoy",
    current_weight: "Peso actual",
    from_start: "desde el inicio",
    weekly_adherence_label: "Adherencia semanal",
    workouts_done_this_week: "{{done}} de {{total}} entrenamientos completados esta semana",
    view_my_workouts: "Ver mis entrenamientos",
    log_my_weight: "Registrar mi peso",
    workout_completed_toast: "¡Entrenamiento completado! 🎉",
    share_in_workouts: "Compártelo en Entrenamientos →",
    close: "Cerrar",
    rest_duration: "{{min}} min descanso",
    rest_seconds: "{{n}}s descanso",
    duration_label: "Duración",
    day_mon: "Lun",
    day_tue: "Mar",
    day_wed: "Mié",
    day_thu: "Jue",
    day_fri: "Vie",
    day_sat: "Sáb",
    day_sun: "Dom",
    light_stretching: "Caminar suave o estirar es perfecto",
    ingredients_n: "{{n}} ingredientes",
    no_meals_today_plan: "Sin comidas planificadas para hoy.",
    meal_plan_after_onboarding: "Tu plan de comidas aparecerá aquí tras el registro.",
    view_meals: "Ver comidas",
    adherence_pct_week: "{{n}}% de adherencia esta semana",
    track_workouts: "Registrar entrenamientos",
    share_progress: "Compartir mi progreso",
    first_exercise: "Primer ejercicio",
    start_workout: "Empezar entreno",
    shopping_pending: "{{n}} pendientes",
    shopping_this_week: "Lista de la compra esta semana",
    view_full_list: "Ver lista completa →",
    view_full_plan: "Ver plan completo →",
    day_streak: "días racha",
    completed_pct: "{{n}}% completado",
    workouts_x_of_y: "{{done}} de {{total}} entrenos",
    target_weight: "Objetivo: {{n}}kg",

    // ── Profile dashboard ─────────────────────────────────────────────────────
    total_workouts: "Total entrenamientos",
    this_month_label: "Este mes",
    streak_days: "Racha de días",
    avg_duration_label: "Duración media",
    weekly_volume_label: "Volumen semanal",
    last_session_label: "Última sesión",
    muscle_groups_label: "Grupos musculares",
    no_sessions_yet: "Sin sesiones aún",
    view_detail_btn: "Ver detalle →",
    vs_prev_week: "vs sem. anterior",
    days_done_fmt: "{{done}} / {{total}} días",
    chart_range_4w: "4S",
    chart_range_3m: "3M",
    chart_range_1y: "1A",
    mins_short: "min",
    hrs_this_week: "hrs esta semana",
    no_data: "Sin datos aún",

    // ── Meals ─────────────────────────────────────────────────────────────────
    weekly_menu: "Menú semanal",
    new_plan: "Nuevo plan",
    breakfast: "Desayuno",
    lunch: "Comida",
    dinner: "Cena",
    snack: "Snack",
    ingredients_portions: "Ingredientes y porciones",
    replace_ingredient: "Cambiar ingrediente",
    generating_meal_plan: "Generando tu nuevo plan de comidas — esto lleva unos 30 segundos…",
    complete_profile_first: "Completa tu perfil primero",
    no_meal_plan_yet: "Sin plan de comidas aún",
    generate_btn: "Generar",
    generate: "Generar",
    cancel_btn: "Cancelar",
    cancel: "Cancelar",
    replace_this_week: "¿Reemplazar las comidas de esta semana con un nuevo plan generado por IA?",
    replace_plan_confirm: "¿Reemplazar las comidas de esta semana con un nuevo plan generado por IA?",
    profile_incomplete: "Perfil incompleto",
    complete_profile_title: "Completa tu perfil primero",
    complete_profile_body: "Necesitamos conocer tu tipo de dieta y objetivo para generar un plan de comidas personalizado.",
    complete_my_profile: "Completar mi perfil",
    no_meal_plan_onboarding: "Completa el registro para que se genere automáticamente tu plan de comidas de 7 días.",
    week_of: "Semana del",
    update_profile: "Actualizar perfil",
    generating_short: "Generando…",
    generation_failed: "Error al generar",
    update_profile_btn: "Actualizar perfil",
    update_now: "Actualizar ahora",
    no_meals_this_day: "Sin comidas planificadas para este día.",
    plate_guide: "Guía del plato",
    distribution: "Distribución",
    pg_protein: "¼ plato",
    pg_carbs: "¼ plato",
    pg_vegetables: "½ plato",
    pg_fruit: "porción pequeña",
    pg_fats: "pequeña cantidad",
    pg_dairy: "porción pequeña",
    pg_other: "al gusto",
    please_complete_profile: "Por favor, completa tu perfil antes de generar un nuevo plan.",
    view_restrictions_arrow: "Ver tus restricciones →",
    no_suitable_alts: "No se encontraron alternativas adecuadas para este ingrediente.",
    could_not_load_swaps: "No se pudieron cargar las opciones. Por favor, inténtalo de nuevo.",
    swap_failed: "Error al cambiar. Por favor, inténtalo de nuevo.",

    // ── Workouts ──────────────────────────────────────────────────────────────
    weekly_training_title: "Entrenamiento semanal",
    todays_focus: "Enfoque de hoy",
    session_focus: "Enfoque de sesión",
    exercises_label: "Ejercicios",
    view_example: "Ver ejemplo",
    view_example_arrow: "Ver ejemplo →",
    rest_label: "Descanso",
    rest_short: "Descanso",
    no_workout_yet: "Sin plan de entrenamiento aún",
    no_workout_plan: "Sin plan de entrenamiento aún",
    training_days_count: "{{n}} días de entrenamiento esta semana",
    rest_recover: "Descanso y recuperación",
    rest_recover_msg: "Los días de descanso son igual de importantes que el entrenamiento. Caminar, estirar o practicar yoga son perfectos hoy.",
    complete_onboarding_workout: "Completa el registro para que se genere automáticamente tu plan de entrenamiento semanal.",
    wt_cardio: "Cardio",
    wt_hiit: "HIIT",
    wt_circuit: "Circuito",
    wt_upper: "Tren superior",
    wt_lower: "Tren inferior",
    wt_full: "Cuerpo completo",
    wt_push: "Día de Empuje",
    wt_pull: "Día de Jalón",
    wt_legs: "Día de Piernas",
    wt_core: "Día de Core",
    wt_cardio_day: "Día de Cardio",
    sets_x_reps: "{{sets}} series × {{reps}} reps",
    rest_duration: "{{duration}} descanso",
    start: "Inicio",
    end: "Final",

    // ── Calendar ──────────────────────────────────────────────────────────────
    calendar_title: "📅 Calendario",
    flex_day_tracker: "Registro Flex Day",
    flex_day_desc: "Día libre en la dieta — come sin restricciones",
    flex_month_count: "{{n}} / 4 este mes",
    flex_limit_exceeded: "Has superado el límite recomendado",
    flex_limit_toast: "Ya tienes {{n}} Flex Days este mes — ¡cuidado con excederte! 😋",
    monthly_adherence: "Adherencia mensual",
    completed_label: "Completado",
    planned_workout: "Entrenamiento planificado",
    rest_day: "Día de descanso",
    flex_day: "Flex Day",
    workouts_done: "{{done}} de {{total}} entrenamientos completados",
    workouts_done_of: "{{done}} de {{total}} entrenamientos completados",
    adherence_perfect_month: "¡Mes perfecto! Todos los entrenamientos completados.",
    adherence_crushing: "¡Lo estás bordando — consistencia de élite!",
    adherence_strong_month: "Mes sólido. Sigue construyendo el hábito.",
    adherence_good_effort: "¡Buen esfuerzo! Aprieta un poco más cada semana.",
    adherence_started: "Has empezado — cada entrenamiento completado cuenta.",
    adherence_fresh_month: "Empieza el mes con fuerza. Pulsa un día de entrenamiento para registrarlo.",
    clean_weeks: "{{n}} semana{{s}} sin saltarse la dieta — ¡fuerza de voluntad impresionante!",
    flex_days_across: "{{n}} flex day{{s}} usados en {{weeks}} semana{{ws}} — el equilibrio es clave.",
    keep_going: "¡sigue así!",
    tap_workout_hint: "Pulsa un día de entrenamiento para marcarlo como completado · Pulsa 😋 para marcar un Flex Day",
    flex_day_used_week: "Ya tienes un Flex Day esta semana 😋",
    only_one_flex: "Solo puedes marcar un Flex Day por semana.",
    could_not_save_flex: "No se pudo guardar el Flex Day. Por favor, inténtalo de nuevo.",
    mark_as_done: "Marcar como hecho",
    confirm: "Confirmar",

    // ── Strength tracking ──────────────────────────────────────────────────────
    log_todays_max: "Registrar máximo de hoy",
    strength_progress: "Progresión de fuerza",
    personal_record: "¡Récord personal!",
    new_pr: "+{{n}}kg nuevo récord",
    prev_record: "Anterior: {{n}}kg",
    save_log: "Guardar",
    no_strength_data: "Empieza a registrar pesos para ver tu progreso",
    select_muscle: "Selecciona grupo muscular",
    muscle_group_shoulders: "Hombros",
    muscle_group_back: "Espalda",
    muscle_group_legs: "Piernas",
    muscle_group_chest: "Pecho",
    muscle_group_arms: "Brazos",
    muscle_group_core: "Core",
    log_timed: "Registrar tiempo",
    target_time: "Objetivo",
    seconds_unit: "seg",
    actual_time: "Tiempo real (seg)",
    log_cardio: "Registrar sesión cardio",
    log_bodyweight: "Registrar repeticiones",
    distance_km: "Distancia (km)",
    duration_min: "Tiempo (min)",
    pace_label: "Ritmo (min/km)",
    heart_rate: "FC media (ppm)",
    sets_done: "Series hechas",
    optional_field: "Opcional",

    // ── Shopping ──────────────────────────────────────────────────────────────
    shopping_list: "Lista de la compra",
    vegetables: "Verduras",
    fruits: "Frutas",
    fruit: "Fruta",
    protein: "Proteína",
    dairy: "Lácteos",
    carbs: "Carbohidratos",
    carbohydrates: "Carbohidratos",
    fat: "Grasas",
    fats: "Grasas",
    other: "Otros",
    add_custom_item: "Añadir artículo",
    clear_purchased: "Limpiar",
    clear: "Limpiar",
    category_label: "Categoría",
    supermarket_label: "Supermercado",
    optimize_label: "Optimizar",
    purchased_count: "{{n}} de {{total}} comprados",
    all_purchased: "¡Todo comprado! 🎉",
    items_label: "artículos",
    cat_done_label: "HECHO ✓",
    categories_label: "categorías",
    custom_label: "personalizados",
    show_n: "Mostrar ({{n}})",
    hide_n: "Ocultar ({{n}})",
    updates_automatically: "Se actualiza automáticamente al cambiar ingredientes",
    most_needed: "Los más necesarios primero — ordenados por número de comidas",
    no_meal_plan_shopping: "Genera tu plan de comidas semanal para obtener tu lista de la compra personalizada.",
    go_to_meals: "Ir a comidas",

    // ── Progress ──────────────────────────────────────────────────────────────
    progress_title: "📈 Progreso",
    weight_title: "Peso",
    log_weight: "Registrar peso",
    log_today_weight: "Registrar peso de hoy",
    current_weight: "Peso actual",
    start_weight: "Peso inicial",
    target_weight: "Objetivo",
    your_goal: "Tu objetivo",
    save_btn: "Guardar",
    saved: "¡Guardado!",
    kg_logged: "¡{{n}} kg registrados!",
    workouts_done_label: "Entrenamientos hechos",
    weekly_adherence_label: "Adherencia semanal",
    weight_over_time: "Evolución del peso",
    your_journey: "Tu progreso hasta ahora",
    recent_entries: "Registros recientes",
    no_target_weight: "Sin peso objetivo",
    every_workout_counts: "Cada entrenamiento cuenta 🎯",
    this_week_short: "esta semana",
    press_plus: "Pulsa + para guardar tu peso",
    eg_weight: "ej. 72.5",
    not_enough_data: "Aún no hay suficientes datos",
    log_to_see_trend: "Registra tu peso varias veces para ver tu tendencia",
    goal_reached: "🎉 ¡Objetivo alcanzado!",
    kg_to_go: "{{n}} kg para llegar",
    log_first_weigh_in: "Registra tu primer peso abajo",
    from_start: "desde el inicio",
    down_kg_progress: "Bajaste {{n}} kg — ¡gran progreso!",
    up_kg_from_start: "Subiste {{n}} kg desde el inicio",
    weight_stable: "Peso estable desde que empezaste",
    goal_hit_congrats: "¡Has alcanzado tu peso objetivo — increíble!",
    kg_to_goal_over: "{{n}} kg para tu objetivo. ¡Sigue así — vas en la dirección correcta!",
    kg_to_goal_almost: "{{n}} kg para tu objetivo. ¡Casi estás!",
    great_tracking: "Buen trabajo registrando hoy. La consistencia lo es todo.",
    trending_right: "{{n}} kg para tu objetivo. Vas en la dirección correcta — sé consistente.",
    keep_logging: "Sigue registrando tu peso para seguir tu evolución.",
    normal_muscle_gain: "Esto es normal — el aumento de músculo puede verse como aumento de peso. Sigue el plan y confía en él.",
    consistency_logging: "La consistencia en el registro revelará tu tendencia con el tiempo. ¡Sigue así!",
    adherence_excellent: "¡Excelente! Sigue así 🏆",
    adherence_good_progress: "Buen progreso 💪",

    // ── Profile page ──────────────────────────────────────────────────────────
    profile_title: "Mi perfil y preferencias",
    profile_subtitle: "Aplicado a cada plan de comidas y cambio de ingrediente",
    profile_incomplete_title: "Tu perfil está incompleto",
    profile_incomplete_body: "Completa tu perfil para generar tu plan de comidas personalizado. Faltan:",
    complete_my_profile_btn: "Completar mi perfil",
    your_name: "Tu nombre",
    diet_type_label: "Tipo de dieta",
    goal_label: "Objetivo",
    allergies_label: "Alergias",
    intolerances_label: "Intolerancias",
    disliked_foods_label: "Alimentos no deseados",
    favourite_foods_label: "Alimentos favoritos",
    name_not_set: "No establecido — añade tu nombre en Actualizar preferencias",
    not_set_complete: "No establecido — por favor completa tu perfil",
    no_allergies: "Sin alergias registradas",
    no_dislikes: "Sin rechazos registrados",
    no_favourites: "Sin favoritos registrados",
    missing_badge: "Falta",
    restrictions_applied: "Tus restricciones dietéticas se aplican a cada plan de comidas, lista de la compra y cambio de ingrediente.",
    strictly_excluded: "Estos están estrictamente excluidos de todas las comidas generadas y cambios de ingredientes — incluyendo todos sus derivados.",
    dislikes_excluded: "Estos alimentos están excluidos de los planes de comidas y no aparecerán como sugerencias de cambio.",
    ai_includes_likes: "La IA intenta incluir estos alimentos cuando es posible y apropiado para tu dieta.",
    saving_regenerates: "Guardar las preferencias regenerará automáticamente tu plan de comidas en unos 30 segundos.",
    current_label: "Actual",
    update_preferences: "Actualizar preferencias",
    back_to_billing: "Volver a facturación",

    // ── Billing page ──────────────────────────────────────────────────────────
    billing_title: "Suscripción y facturación",
    billing_subtitle: "Gestiona tu plan GoalIQ",
    back_to_dashboard: "Volver al inicio",
    plan_details: "Detalles del plan",
    plan_label: "Plan",
    price_label: "Precio",
    status_label: "Estado",
    trial_ends_label: "La prueba termina",
    billing_monthly_label: "Facturación",
    trial_active_badge: "Prueba activa",
    active_badge: "Activo",
    payment_overdue_badge: "Pago pendiente",
    canceled_badge: "Cancelado",
    no_plan_badge: "Sin plan",
    manage_subscription: "Gestionar suscripción",
    whats_included: "Qué incluye",
    monthly_billing: "Mensual",
    ends_today: "termina hoy",
    one_day_left: "1 día restante",
    n_days_left: "{{n}} días restantes",
    payments_secured: "Pagos gestionados por Stripe · Cancela cuando quieras",
    trial_desc: "Tienes acceso completo durante tu prueba gratuita.",
    active_desc: "Tu suscripción está activa. Acceso completo habilitado.",
    past_due_desc: "Tu último pago falló. Actualiza tu método de pago para mantener el acceso.",
    canceled_desc: "Tu suscripción fue cancelada. Vuelve a suscribirte para recuperar el acceso.",
    no_plan_resubscribe: "Vuelve a suscribirte por €19.99/mes para restaurar el acceso completo.",
    no_plan_trial: "Empieza tu prueba gratuita para desbloquear todas las funciones.",
    feat_meal_plan: "Plan de comidas personalizado de 7 días completo",
    feat_workout: "Horario semanal de entrenamiento completo",
    feat_ingredient_swap: "Cambio de ingredientes (con IA)",
    feat_weight: "Seguimiento de peso y gráficos de progreso",
    feat_insights: "Consejos de coaching inteligente",
    feat_streak: "Seguimiento de rachas y calendario",

    // ── Pricing / Trial Copy ───────────────────────────────────────────────────
    back_to_home: "Volver al inicio",
    one_plan_everything: "SIN EXCUSAS. TODO DEPENDE DE TI.",
    go_to_dashboard: "Ir al panel",
    per_month: "/mes",
    price_monthly_display: "19,99€/mes",
    after_trial_note: "Tras la prueba, se te cobrará 19,99€/mes. Cancela cuando quieras — sin preguntas.",
    pricing_manage: "Gestionar",
    pricing_status_trial: "Prueba gratuita",
    pricing_status_active: "Activo",
    pricing_status_past_due: "Pago pendiente",
    pricing_status_canceled: "Cancelado",
    pricing_status_unpaid: "Sin pagar",
    confirming_with_stripe: "Confirmando tu suscripción con Stripe",
    page_workout_plan: "Plan de Entrenamiento",
    page_workout_calendar: "Calendario de Entrenamientos",
    page_meal_plan: "Plan de Comidas",
    page_shopping_list: "Lista de la Compra",
    page_progress: "Seguimiento de Progreso",
    unlock_full_access: "Desbloquear acceso completo",
    pricing_feat_1: "Plan de comidas personalizado de 7 días",
    pricing_feat_shopping: "🛒 Lista de la compra automática — generada desde tu plan semanal",
    pricing_feat_2: "Plan de entrenamiento semanal completo",
    pricing_feat_3: "Cambio de ingredientes con IA",
    pricing_feat_4: "Seguimiento de peso y gráficos de progreso",
    pricing_feat_5: "Insights de coaching inteligente",
    pricing_feat_6: "Seguimiento de rachas y estadísticas",
    pricing_feat_7: "Calendario con registro de entrenamientos",
    pricing_feat_8: "Análisis de tendencia de peso",
    trial_feat_1: "Plan de comidas personalizado de 7 días",
    trial_feat_2: "Plan de entrenamiento semanal completo",
    trial_feat_3: "Cambio de ingredientes con IA",
    trial_feat_4: "Seguimiento de peso y progreso",
    trial_feat_5: "Insights de coaching inteligente y rachas",
    tc_tagline: "Gratis 3 días — luego 19,99€/mes. Cancela cuando quieras.",
    tc_tagline_short: "Sin cargo 3 días · Cancela cuando quieras",
    tc_badge: "PRUEBA GRATIS 3 DÍAS",
    tc_price_after_trial: "Gratis 3 días, luego 19,99€/mes · Cancela cuando quieras",
    tc_pricing_subheading: "Tu nutricionista y entrenador personal en el bolsillo. Sin compromisos.",
    tc_secured_by_stripe: "Gestionado por Stripe · Sin cargo durante la prueba",
    tc_full_access_trial: "Acceso completo durante tu prueba de 3 días",
    tc_available_trial: "Disponible durante tu prueba gratuita de 3 días y con suscripción activa.",
    tc_cta_start: "Empezar prueba gratis de 3 días",
    tc_cta_start_short: "Empezar prueba gratuita",
    tc_cta_signup: "Registrarse y empezar prueba gratuita",
    tc_cta_redirecting: "Redirigiendo al pago…",
    tc_cta_subscribe: "Suscribirse",
    tc_cta_resubscribe: "Volver a suscribirte",
    tc_cta_add_payment: "Añadir método de pago",
    tc_cta_unlock: "Prueba — Desbloquear",
    tc_cta_start_free: "Empezar prueba gratuita",
    tc_trial_note: "Prueba de 3 días · Sin cargo hoy · Cancela cuando quieras",
    tc_no_card_charge: "0€ durante tu prueba de 3 días · Cancela cuando quieras",
    tc_resubscribe_title: "Recupera tu acceso completo",
    tc_resubscribe_subtitle: "Vuelve a suscribirte por 19,99€/mes y continúa con tus planes de comidas, entrenamientos y progreso.",
    tc_resubscribe_badge: "VOLVER A SUSCRIBIRSE",
    tc_resubscribe_price_note: "19,99€/mes · Facturación mensual · Cancela cuando quieras",
    tc_resubscribe_cta: "Vuelve a suscribirte por 19,99€/mes",
    tc_resubscribe_note: "Facturación mensual · Cancela cuando quieras",
    tc_resubscribe_secured: "Gestionado por Stripe · Facturación mensual",
    tc_resubscribe_gate: "Tu suscripción ha terminado. Vuelve a suscribirte para recuperar el acceso completo.",
    tc_countdown_ends_today: "Tu prueba gratuita termina hoy",
    tc_countdown_one_day: "1 día restante en tu prueba gratuita",
    tc_countdown_n_days: "{{n}} días restantes en tu prueba gratuita",
    tc_countdown_cta: "Suscribirse",
    tc_countdown_urgent: "No pierdas tu plan personalizado — suscríbete para mantener el acceso",
    tc_countdown_enjoy: "Suscríbete ahora para conservar tu plan personalizado y progreso tras la prueba",
    tc_payment_overdue: "Tu pago está pendiente. Actualiza tu método de pago para continuar.",
    tc_sub_canceled: "Tu suscripción fue cancelada. Vuelve a suscribirte para recuperar el acceso.",
    tc_success_title: "¡Todo listo!",
    tc_success_body: "Tu prueba gratuita de 3 días ha comenzado. Disfruta del acceso completo a GoalIQ — sin cargo hasta que termine tu prueba.",
    tc_success_footer: "Te avisaremos antes de que termine tu prueba. Cancela cuando quieras desde la página de facturación.",
    tc_success_redirecting: "Llevándote a tu panel…",
    tc_resub_success_body: "Tu suscripción está activa. Bienvenido de vuelta — el acceso completo ha sido restaurado.",
    tc_resub_success_footer: "Se te cobrará 19,99€/mes. Cancela cuando quieras desde la página de facturación.",
    tc_activating_subscription: "Activando tu suscripción…",
    tc_activating_trial: "Activando tu prueba…",

    // ── Onboarding ────────────────────────────────────────────────────────────
    onboarding_step_about: "Sobre ti",
    onboarding_step_diet: "Tu dieta",
    onboarding_step_fitness: "Tu forma física",
    onboarding_subtitle_about: "Ayúdanos a personalizar tu plan",
    onboarding_subtitle_diet: "Lo que comes y te gusta",
    onboarding_subtitle_fitness: "Cómo te gusta moverte",
    loading_preferences: "Cargando tus preferencias…",
    updating_preferences_msg: "Actualizando tus preferencias — tu plan de comidas se regenerará automáticamente al guardar.",
    what_call_you: "¿Cómo te llamamos?",
    personalise_hint: "Esto nos ayuda a personalizar tu experiencia de coaching.",
    how_old: "¿Cuántos años tienes?",
    bio_sex: "Sexo biológico",
    sex_male: "Hombre",
    sex_female: "Mujer",
    sex_other: "Otro",
    height_cm: "Altura (cm)",
    current_weight_kg: "Peso actual (kg)",
    main_goal: "¿Cuál es tu objetivo principal?",
    goal_lose_fat: "Perder grasa",
    goal_stay_fit: "Mantenerme",
    goal_build_muscle: "Ganar músculo",
    target_weight_kg: "Peso objetivo (kg)",
    diet_type_question: "¿Qué tipo de dieta sigues?",
    diet_balanced: "Equilibrada",
    diet_high_protein: "Alta en proteínas",
    diet_keto: "Keto",
    diet_vegetarian: "Vegetariana",
    diet_vegan: "Vegana",
    food_allergies: "¿Alguna alergia alimentaria?",
    leave_blank: "Déjalo en blanco si no tienes",
    allergies_placeholder: "ej. nueces, lácteos, mariscos",
    foods_avoid: "¿Alimentos que prefieres evitar?",
    foods_avoid_placeholder: "ej. champiñones, aceitunas, brócoli",
    foods_love: "¿Alimentos que te encantan?",
    foods_love_hint: "La IA intentará incluirlos",
    foods_love_placeholder: "ej. pollo, aguacate, frutos rojos",
    fitness_level: "¿Cuál es tu nivel de forma física?",
    fitness_beginner: "Principiante",
    fitness_intermediate: "Intermedio",
    fitness_advanced: "Avanzado",
    where_workout: "¿Dónde prefieres entrenar?",
    gym: "Gimnasio",
    home: "Casa",
    outdoor: "Exterior",
    training_days_slider: "¿Cuántos días por semana puedes entrenar? — {{n}} días",
    one_day: "1 día",
    seven_days: "7 días",
    couldnt_save_prefs: "No se pudieron guardar las preferencias",
    couldnt_create_plan: "No se pudo crear tu plan",
    back: "Atrás",
    continue_btn: "Continuar",
    saving_regenerating: "Guardando y regenerando…",
    creating_plan: "Creando tu plan...",
    save_regenerate: "Guardar y regenerar plan",
    lets_go: "¡Vamos!",
    step_n_of_m: "Paso {{n}} de {{m}}",
    update_prefix: "Actualizar:",
    new_plan_30s: "Tu nuevo plan de comidas estará listo en unos 30 segundos",
    can_update_later: "Siempre puedes actualizarlo más tarde",
    target_weight_placeholder: "ej. 65",
    name_placeholder: "ej. Alex",

    // ── Buttons ───────────────────────────────────────────────────────────────
    start_free_trial: "Empezar prueba gratis",
    generate_new_plan: "Generar nuevo plan",

    // ── Dashboard feedback messages ───────────────────────────────────────────
    fb_fire_title_name: "¡Estás en racha, {{name}}!",
    fb_fire_title: "¡Estás en racha!",
    fb_fire_msg: "{{n}} sesiones de entrenamiento seguidas. Eso es consistencia de élite — la mayoría nunca llega aquí.",
    fb_fire_tip: "La recuperación también importa — duerme 7-9h y come suficiente proteína.",
    fb_streak_title: "Construyendo un gran impulso",
    fb_streak_msg: "{{n}} días de entrenamiento seguidos y contando. Así es como se forjan los hábitos duraderos.",
    fb_streak_tip: "¡Sigue así — al llegar a 7 días ganas tu primera insignia de llama!",
    fb_done_title: "¡Entrenamiento de hoy: completado!",
    fb_done_msg_name: "{{name}}, te presentaste y lo lograste. Descansa, come bien y deja que tu cuerpo se recupere.",
    fb_done_msg: "Te presentaste y lo lograste. Descansa, come bien y deja que tu cuerpo se recupere y crezca.",
    fb_done_tip: "Nutrición post-entrenamiento: proteína + carbohidratos en los primeros 30-60 minutos.",
    fb_perfect_title_name: "¡Semana perfecta, {{name}}!",
    fb_perfect_title: "¡Semana perfecta hasta ahora!",
    fb_perfect_msg: "Todos los entrenamientos planificados completados. Has puesto el listón y lo has superado.",
    fb_perfect_tip: "Celebra las pequeñas victorias — se acumulan en grandes resultados.",
    fb_solid_title: "Buena semana en progreso",
    fb_solid_msg: "{{done}} de {{total}} entrenamientos completados. Estás siendo consistente — eso es lo que importa.",
    fb_solid_tip_more: "¡Un entrenamiento más para que sea perfecta!",
    fb_keep_title: "Mantén el impulso",
    fb_keep_msg: "{{done}} de {{total}} completados esta semana. Cada sesión que completas hace la siguiente más fácil.",
    fb_keep_tip: "Consejo: Programa tu próximo entrenamiento ahora mismo — trátalo como una reunión que no puedes cancelar.",
    fb_started_title: "Has empezado — eso es enorme",
    fb_started_msg: "Un entrenamiento hecho esta semana. El primero siempre es el más difícil. Ahora construye sobre él.",
    fb_started_tip: "Los estudios muestran que las personas con 2+ entrenamientos/semana tienen un 80% más de probabilidades de mantenerlo a largo plazo.",
    fb_fresh_title: "Una nueva semana, un nuevo comienzo",
    fb_fresh_msg: "Tus entrenamientos están planificados y esperando. Todo campeón empezó exactamente donde estás tú ahora.",
    fb_fresh_tip: "Incluso 20 minutos cuentan. Empieza pequeño, sé consistente.",
    fb_rest_title: "Descanso y recarga hoy",
    fb_rest_msg: "La recuperación es parte del plan. Mantente hidratado, come bien y deja que tu cuerpo haga su trabajo.",
    badge_streak_fire: "Racha de {{n}} días 🔥",
    badge_streak_zap: "Racha de {{n}} días ⚡",
    badge_perfect: "Semana perfecta 🏆",
    badge_done: "Hecho por hoy ✓",

    // ── Calendar flex day feedback ─────────────────────────────────────────────
    flex_none_msg: "Sin flex days este mes — ¡gran disciplina!",
    flex_used_msg: "{{n}} flex day{{s}} usados en {{weeks}} semana{{ws}} — el equilibrio es clave.",

    done_name: "¡Listo, {{name}}!",
    done: "¡Listo!",

    // ── Settings ──────────────────────────────────────────────────────────────
    nav_settings: "Ajustes",
    settings_title: "Ajustes",
    appearance: "Apariencia",
    dark_mode: "Oscuro",
    light_mode: "Claro",
    language_section: "Idioma",
    lang_spanish: "Español",
    lang_english: "English",
    lang_subtitle_es: "España",
    lang_subtitle_en: "United Kingdom",
  },
};

type Vars = Record<string, string | number>;

function interpolate(str: string, vars?: Vars): string {
  if (!vars) return str;
  return Object.entries(vars).reduce(
    (s, [k, v]) => s.replaceAll(`{{${k}}}`, String(v)),
    str,
  );
}

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Vars) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "es",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem(LS_KEY);
      if (saved === "en" || saved === "es") return saved;
    } catch {}
    return "es";
  });

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem(LS_KEY, l);
  }

  function t(key: string, vars?: Vars): string {
    const str = T[lang][key] ?? T["en"][key] ?? key;
    return interpolate(str, vars);
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function useT() {
  return useContext(LanguageContext).t;
}

const FLAG: Record<Lang, string> = { en: "🇬🇧", es: "🇪🇸" };
const LABEL: Record<Lang, string> = { en: "English", es: "Español" };
const LANGS: Lang[] = ["en", "es"];

export function LanguageSwitcher() {
  const { lang, setLang } = useLanguage();
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-8 h-8 flex items-center justify-center rounded-md hover:bg-[#2A2A2A] transition-colors text-xl leading-none"
        aria-label="Select language"
        title={LABEL[lang]}
      >
        {FLAG[lang]}
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-1.5 bg-[#1A1A1A] border border-[#2A2A2A] rounded-lg shadow-2xl overflow-hidden z-50 min-w-[130px]">
          {LANGS.map(l => (
            <button
              key={l}
              onClick={() => { setLang(l); setOpen(false); }}
              className="w-full flex items-center gap-2.5 px-3 py-2.5 text-sm text-left hover:bg-[#2A2A2A] transition-colors"
            >
              <span className="text-lg leading-none">{FLAG[l]}</span>
              <span className={`font-medium ${lang === l ? "text-[#AAFF45]" : "text-[#A0A0A0]"}`}>
                {LABEL[l]}
              </span>
              {lang === l && (
                <span className="ml-auto w-1.5 h-1.5 rounded-full bg-[#AAFF45] shrink-0" />
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

const DAY_KEY_MAP: Record<string, string> = {
  monday: "day_mon", tuesday: "day_tue", wednesday: "day_wed",
  thursday: "day_thu", friday: "day_fri", saturday: "day_sat", sunday: "day_sun",
  mon: "day_mon", tue: "day_tue", wed: "day_wed", thu: "day_thu",
  fri: "day_fri", sat: "day_sat", sun: "day_sun",
};

export function translateDay(day: string, t: (key: string) => string): string {
  const key = DAY_KEY_MAP[day.toLowerCase()];
  return key ? t(key) : day;
}
